version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/codedeploy/be/v1/
    permissions:
      - object: /home/deploy/codedeploy/be/v1
        pattern: "**"
        owner: deploy
        group: deploy
        mode: 644
        type:
          - file
      - object: /home/deploy/codedeploy/be/v1
        pattern: "**"
        owner: deploy
        group: deploy
        mode: 755
        type:
          - directory    
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 300
      runas: deploy
